import type { NutritionModuleData } from "@/features/bettertolive/models/workspace"

export const nutritionFixtureData: NutritionModuleData = {
  profile: {
    hardConstraints: [],
    softStances: [],
    currentIntent: { mode: "维持", note: "" },
  },
  foodCategories: [
    { id: "cat-staple", name: "主食", dimension: "食物大类", description: "", sortOrder: 1 },
    { id: "cat-ready", name: "即食", dimension: "食物大类", description: "", sortOrder: 2 },
    { id: "cat-protein", name: "蛋白质", dimension: "食物大类", description: "", sortOrder: 3 },
    { id: "cat-produce", name: "蔬果", dimension: "食物大类", description: "", sortOrder: 4 },
    { id: "cat-raw", name: "生鲜", dimension: "食物大类", description: "", sortOrder: 5 },
    { id: "cat-fridge", name: "冷藏", dimension: "食物大类", description: "", sortOrder: 6 },
    {
      id: "cat-staple-stock",
      name: "主食储备",
      dimension: "食物大类",
      description: "",
      sortOrder: 7,
    },
  ],
  foods: [
    {
      id: "food-apple",
      name: "苹果",
      categoryIds: ["cat-produce", "cat-ready"],
      defaultUnit: "个",
      storage: "常温",
      lifecycle: "新鲜短期",
      allergenTags: [],
      dietaryTags: ["素食"],
      nutrientProfileId: "nutrient-apple",
    },
    {
      id: "food-juice",
      name: "100%果汁",
      categoryIds: ["cat-produce", "cat-ready"],
      defaultUnit: "ml",
      storage: "冷藏",
      lifecycle: "饮品",
      allergenTags: [],
      dietaryTags: ["素食"],
      nutrientProfileId: "nutrient-juice",
    },
    {
      id: "food-edamame",
      name: "毛豆",
      categoryIds: ["cat-protein", "cat-produce", "cat-raw", "cat-fridge"],
      defaultUnit: "g",
      storage: "冷藏",
      lifecycle: "新鲜短期",
      allergenTags: ["大豆"],
      dietaryTags: ["素食"],
      nutrientProfileId: "nutrient-edamame",
    },
    {
      id: "food-pickle",
      name: "咸菜",
      categoryIds: ["cat-ready", "cat-staple-stock"],
      defaultUnit: "g",
      storage: "冷藏",
      lifecycle: "调味",
      allergenTags: [],
      dietaryTags: ["素食"],
      nutrientProfileId: "nutrient-pickle",
    },
    {
      id: "food-milk-tea",
      name: "全糖奶茶",
      categoryIds: ["cat-ready"],
      defaultUnit: "ml",
      storage: "即食",
      lifecycle: "饮品",
      allergenTags: ["乳制品"],
      dietaryTags: [],
      nutrientProfileId: "nutrient-milk-tea",
    },
    {
      id: "food-instant-noodle",
      name: "方便面",
      categoryIds: ["cat-staple", "cat-ready", "cat-staple-stock"],
      defaultUnit: "份",
      storage: "常温",
      lifecycle: "常备",
      allergenTags: ["麸质"],
      dietaryTags: [],
      nutrientProfileId: "nutrient-instant-noodle",
    },
    {
      id: "food-luncheon-meat",
      name: "午餐肉",
      categoryIds: ["cat-protein", "cat-ready", "cat-staple-stock"],
      defaultUnit: "g",
      storage: "常温",
      lifecycle: "常备",
      allergenTags: [],
      dietaryTags: [],
      nutrientProfileId: "nutrient-luncheon-meat",
    },
    {
      id: "food-oats",
      name: "燕麦片",
      categoryIds: ["cat-staple", "cat-ready", "cat-staple-stock"],
      defaultUnit: "g",
      storage: "常温",
      lifecycle: "干货",
      allergenTags: ["麸质"],
      dietaryTags: ["素食"],
      nutrientProfileId: "nutrient-oats",
    },
    {
      id: "food-soy-milk",
      name: "无糖豆奶",
      categoryIds: ["cat-protein", "cat-ready", "cat-fridge"],
      defaultUnit: "ml",
      storage: "冷藏",
      lifecycle: "饮品",
      allergenTags: ["大豆"],
      dietaryTags: ["素食"],
      nutrientProfileId: "nutrient-soy-milk",
    },
    {
      id: "food-rice",
      name: "白米饭",
      categoryIds: ["cat-staple", "cat-ready", "cat-staple-stock"],
      defaultUnit: "g",
      storage: "冷藏",
      lifecycle: "常备",
      allergenTags: [],
      dietaryTags: [],
      nutrientProfileId: "nutrient-white-rice",
    },
    {
      id: "food-fish",
      name: "鲈鱼",
      categoryIds: ["cat-protein", "cat-raw", "cat-fridge"],
      defaultUnit: "g",
      storage: "冷藏",
      lifecycle: "新鲜短期",
      allergenTags: ["鱼"],
      dietaryTags: [],
      nutrientProfileId: "nutrient-fish",
    },
    {
      id: "food-greens",
      name: "青菜",
      categoryIds: ["cat-produce", "cat-raw", "cat-fridge"],
      defaultUnit: "g",
      storage: "冷藏",
      lifecycle: "新鲜短期",
      allergenTags: [],
      dietaryTags: ["素食"],
      nutrientProfileId: "nutrient-greens",
    },
    {
      id: "food-brown-rice",
      name: "杂粮饭",
      categoryIds: ["cat-staple", "cat-ready", "cat-staple-stock"],
      defaultUnit: "g",
      storage: "冷藏",
      lifecycle: "常备",
      allergenTags: [],
      dietaryTags: ["素食"],
      nutrientProfileId: "nutrient-brown-rice",
    },
  ],
  nutrientProfiles: [
    {
      id: "nutrient-apple",
      foodId: "food-apple",
      basisAmount: 100,
      basisUnit: "g",
      energyKcal: 52,
      proteinG: 0.3,
      fatG: 0.2,
      carbG: 14,
      fiberG: 2.4,
      sugarG: 10,
      sodiumMg: 1,
      source: "食物成分表",
      confidence: "高",
      saturatedFatG: 0,
      addedSugarG: 0,
      calciumMg: 6,
      ironMg: 0.1,
      potassiumMg: 107,
      sugarKind: "天然存在",
      processingLevel: "原食材",
      sodiumRiskLevel: "低",
      proteinSource: "豆类",
    },
    {
      id: "nutrient-juice",
      foodId: "food-juice",
      basisAmount: 100,
      basisUnit: "ml",
      energyKcal: 45,
      proteinG: 0.5,
      fatG: 0.1,
      carbG: 10,
      fiberG: 0.2,
      sugarG: 9,
      sodiumMg: 2,
      source: "食物成分表",
      confidence: "高",
      saturatedFatG: 0,
      addedSugarG: 0,
      calciumMg: 8,
      ironMg: 0.2,
      potassiumMg: 90,
      sugarKind: "游离糖/添加糖",
      processingLevel: "高度加工",
      sodiumRiskLevel: "低",
      proteinSource: "豆类",
    },
    {
      id: "nutrient-edamame",
      foodId: "food-edamame",
      basisAmount: 100,
      basisUnit: "g",
      energyKcal: 121,
      proteinG: 11.9,
      fatG: 5.2,
      carbG: 8.9,
      fiberG: 5.2,
      sugarG: 2.2,
      sodiumMg: 6,
      source: "食物成分表",
      confidence: "高",
      saturatedFatG: 0.6,
      addedSugarG: 0,
      calciumMg: 63,
      ironMg: 2.3,
      potassiumMg: 436,
      sugarKind: "天然存在",
      processingLevel: "原食材",
      sodiumRiskLevel: "低",
      proteinSource: "豆类",
    },
    {
      id: "nutrient-pickle",
      foodId: "food-pickle",
      basisAmount: 100,
      basisUnit: "g",
      energyKcal: 15,
      proteinG: 1,
      fatG: 0.2,
      carbG: 2.5,
      fiberG: 1.2,
      sugarG: 1,
      sodiumMg: 1500,
      source: "食物成分表",
      confidence: "中",
      saturatedFatG: 0,
      addedSugarG: 0,
      calciumMg: 30,
      ironMg: 0.8,
      potassiumMg: 100,
      sugarKind: "天然存在",
      processingLevel: "高度加工",
      sodiumRiskLevel: "高",
      proteinSource: "豆类",
    },
    {
      id: "nutrient-milk-tea",
      foodId: "food-milk-tea",
      basisAmount: 100,
      basisUnit: "ml",
      energyKcal: 60,
      proteinG: 0.8,
      fatG: 1.5,
      carbG: 10,
      fiberG: 0,
      sugarG: 9,
      sodiumMg: 30,
      source: "包装",
      confidence: "中",
      saturatedFatG: 0.8,
      addedSugarG: 7,
      calciumMg: 50,
      ironMg: 0.1,
      potassiumMg: 80,
      sugarKind: "游离糖/添加糖",
      processingLevel: "高度加工",
      sodiumRiskLevel: "低",
      proteinSource: "奶类",
    },
    {
      id: "nutrient-instant-noodle",
      foodId: "food-instant-noodle",
      basisAmount: 100,
      basisUnit: "g",
      energyKcal: 450,
      proteinG: 8,
      fatG: 18,
      carbG: 62,
      fiberG: 2,
      sugarG: 2,
      sodiumMg: 800,
      source: "包装",
      confidence: "中",
      saturatedFatG: 8,
      addedSugarG: 0,
      calciumMg: 20,
      ironMg: 2.5,
      potassiumMg: 120,
      sugarKind: "天然存在",
      processingLevel: "高度加工",
      sodiumRiskLevel: "高",
      proteinSource: "豆类",
    },
    {
      id: "nutrient-luncheon-meat",
      foodId: "food-luncheon-meat",
      basisAmount: 100,
      basisUnit: "g",
      energyKcal: 240,
      proteinG: 12,
      fatG: 20,
      carbG: 3,
      fiberG: 0,
      sugarG: 1,
      sodiumMg: 900,
      source: "包装",
      confidence: "中",
      saturatedFatG: 7,
      addedSugarG: 0,
      calciumMg: 10,
      ironMg: 1.5,
      potassiumMg: 150,
      sugarKind: "天然存在",
      processingLevel: "高度加工",
      sodiumRiskLevel: "高",
      proteinSource: "加工肉",
    },
    {
      id: "nutrient-oats",
      foodId: "food-oats",
      basisAmount: 100,
      basisUnit: "g",
      energyKcal: 389,
      proteinG: 16.9,
      fatG: 6.9,
      carbG: 66,
      fiberG: 10.6,
      sugarG: 1,
      sodiumMg: 2,
      source: "食物成分表",
      confidence: "高",
      saturatedFatG: 1.2,
      addedSugarG: 0,
      calciumMg: 54,
      ironMg: 4.7,
      potassiumMg: 362,
      sugarKind: "天然存在",
      processingLevel: "轻加工",
      sodiumRiskLevel: "低",
      proteinSource: "豆类",
    },
    {
      id: "nutrient-soy-milk",
      foodId: "food-soy-milk",
      basisAmount: 100,
      basisUnit: "ml",
      energyKcal: 33,
      proteinG: 3.3,
      fatG: 1.5,
      carbG: 1.2,
      fiberG: 0.4,
      sugarG: 0.5,
      sodiumMg: 50,
      source: "包装",
      confidence: "中",
      saturatedFatG: 0.2,
      addedSugarG: 0,
      calciumMg: 120,
      ironMg: 0.6,
      potassiumMg: 120,
      sugarKind: "天然存在",
      processingLevel: "高度加工",
      sodiumRiskLevel: "低",
      proteinSource: "豆制品",
    },
    {
      id: "nutrient-white-rice",
      foodId: "food-rice",
      basisAmount: 100,
      basisUnit: "g",
      energyKcal: 130,
      proteinG: 2.7,
      fatG: 0.3,
      carbG: 28,
      fiberG: 0.4,
      sugarG: 0,
      sodiumMg: 1,
      source: "食物成分表",
      confidence: "高",
      saturatedFatG: 0.1,
      addedSugarG: 0,
      calciumMg: 10,
      ironMg: 0.2,
      potassiumMg: 35,
      sugarKind: "天然存在",
      processingLevel: "轻加工",
      sodiumRiskLevel: "低",
      proteinSource: "豆类",
    },
    {
      id: "nutrient-fish",
      foodId: "food-fish",
      basisAmount: 100,
      basisUnit: "g",
      energyKcal: 105,
      proteinG: 18.6,
      fatG: 3.4,
      carbG: 0,
      fiberG: 0,
      sugarG: 0,
      sodiumMg: 68,
      source: "食物成分表",
      confidence: "高",
      saturatedFatG: 0.8,
      addedSugarG: 0,
      calciumMg: 12,
      ironMg: 0.5,
      potassiumMg: 344,
      sugarKind: "天然存在",
      processingLevel: "原食材",
      sodiumRiskLevel: "低",
      proteinSource: "鱼虾海鲜",
    },
    {
      id: "nutrient-greens",
      foodId: "food-greens",
      basisAmount: 100,
      basisUnit: "g",
      energyKcal: 18,
      proteinG: 1.7,
      fatG: 0.2,
      carbG: 3.2,
      fiberG: 1.6,
      sugarG: 0.8,
      sodiumMg: 40,
      source: "食物成分表",
      confidence: "高",
      saturatedFatG: 0,
      addedSugarG: 0,
      calciumMg: 98,
      ironMg: 1.2,
      potassiumMg: 210,
      sugarKind: "天然存在",
      processingLevel: "原食材",
      sodiumRiskLevel: "低",
    },
    {
      id: "nutrient-brown-rice",
      foodId: "food-brown-rice",
      basisAmount: 100,
      basisUnit: "g",
      energyKcal: 116,
      proteinG: 2.6,
      fatG: 0.9,
      carbG: 23,
      fiberG: 1.8,
      sugarG: 0.2,
      sodiumMg: 3,
      source: "手动",
      confidence: "高",
      saturatedFatG: 0.2,
      addedSugarG: 0,
      calciumMg: 10,
      ironMg: 0.4,
      potassiumMg: 76,
      sugarKind: "天然存在",
      processingLevel: "轻加工",
      sodiumRiskLevel: "低",
    },
  ],
  recipes: [
    {
      id: "recipe-oats-soy-apple",
      name: "燕麦豆奶苹果早餐",
      servings: 1,
      mealRoles: ["早餐"],
      ingredients: [
        { foodId: "food-oats", amount: 50, unit: "g" },
        { foodId: "food-soy-milk", amount: 200, unit: "ml" },
        { foodId: "food-apple", amount: 0.5, unit: "个" },
      ],
      steps: [],
      difficulty: "简单",
      repeatability: "常做",
      tags: ["早餐", "快手"],
    },
    {
      id: "recipe-edamame-rice-bowl",
      name: "毛豆米饭碗",
      servings: 1,
      mealRoles: ["午餐"],
      ingredients: [
        { foodId: "food-rice", amount: 150, unit: "g" },
        { foodId: "food-edamame", amount: 80, unit: "g" },
      ],
      steps: [],
      difficulty: "简单",
      repeatability: "常做",
      tags: ["午餐", "快手"],
    },
    {
      id: "recipe-steamed-fish",
      name: "清蒸鱼",
      servings: 2,
      mealRoles: ["晚餐"],
      ingredients: [
        { foodId: "food-fish", amount: 450, unit: "g" },
        { foodId: "food-greens", amount: 240, unit: "g" },
        { foodId: "food-brown-rice", amount: 260, unit: "g" },
      ],
      steps: [],
      difficulty: "简单",
      repeatability: "常做",
      tags: ["晚餐"],
    },
  ],
  dailyPlans: [
    {
      id: "plan-2026-06-14",
      date: "2026-06-14",
      slots: [
        {
          id: "slot-breakfast",
          structure: "早餐",
          status: "planned",
          entries: [{ type: "recipe", recipeId: "recipe-oats-soy-apple", servings: 1 }],
        },
        {
          id: "slot-lunch",
          structure: "午餐",
          status: "planned",
          entries: [{ type: "recipe", recipeId: "recipe-edamame-rice-bowl", servings: 1 }],
        },
        {
          id: "slot-dinner",
          structure: "晚餐",
          status: "planned",
          entries: [{ type: "recipe", recipeId: "recipe-steamed-fish", servings: 1 }],
        },
      ],
    },
  ],
  mealLogs: [
    {
      id: "log-9",
      dateTime: "2026-06-20T08:00:00",
      scene: "在家做",
      trigger: "准时按点",
      bodyFeedback: "满足舒服",
      valueDensity: "中",
      entries: [{ type: "recipe", recipeId: "recipe-oats-soy-apple", servings: 1 }],
    },
    {
      id: "log-10",
      dateTime: "2026-06-20T15:00:00",
      scene: "加餐零食",
      trigger: "情绪驱动",
      bodyFeedback: "普通",
      valueDensity: "低",
      entries: [
        { type: "food", foodId: "food-juice", amount: 300, unit: "ml" },
        { type: "food", foodId: "food-milk-tea", amount: 500, unit: "ml" },
      ],
    },
    {
      id: "log-11",
      dateTime: "2026-06-21T19:00:00",
      scene: "在家做",
      trigger: "真饿了",
      bodyFeedback: "偏重偏胀",
      valueDensity: "低",
      entries: [
        { type: "food", foodId: "food-instant-noodle", amount: 1, unit: "份" },
        { type: "food", foodId: "food-pickle", amount: 30, unit: "g" },
        { type: "food", foodId: "food-luncheon-meat", amount: 80, unit: "g" },
      ],
    },
  ],
  meals: [],
  weeklyReview: { highlights: [], missingSignals: [], crossViews: [] },
  foodMemories: [],
}
