import { readFileSync, writeFileSync } from "fs"
import { join, dirname } from "path"
import { fileURLToPath } from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, "..")

const { version } = JSON.parse(readFileSync(join(root, "package.json"), "utf8"))

const cargoPath = join(root, "src-tauri", "Cargo.toml")
let cargo = readFileSync(cargoPath, "utf8")
cargo = cargo.replace(/^(version\s*=\s*")\d+\.\d+\.\d+(")/m, `$1${version}$2`)
writeFileSync(cargoPath, cargo)

const confPath = join(root, "src-tauri", "tauri.conf.json")
const conf = JSON.parse(readFileSync(confPath, "utf8"))
conf.version = version
writeFileSync(confPath, JSON.stringify(conf, null, 2) + "\n")

const versionTsPath = join(root, "src", "shared", "version.ts")
const versionTs = `// This file is auto-generated by scripts/sync-version.mjs.
// Do not edit manually.
export const APP_VERSION = ${JSON.stringify(version)}
`
writeFileSync(versionTsPath, versionTs)

console.log(`Synced version to v${version}`)
