// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	/**  Returns the full shopping module content aggregated from relational tables. */
	getShopping: () => typedError<ShoppingModuleDto_Serialize, string>(__TAURI_INVOKE("get_shopping")),
	listOwnedItems: () => typedError<OwnedItemRow[], string>(__TAURI_INVOKE("list_owned_items")),
	createOwnedItem: (form: OwnedItemFormDto) => typedError<ShoppingOwnedItemDto_Serialize, string>(__TAURI_INVOKE("create_owned_item", { form })),
	updateOwnedItem: (form: OwnedItemFormDto) => typedError<ShoppingOwnedItemDto_Serialize, string>(__TAURI_INVOKE("update_owned_item", { form })),
	deleteOwnedItem: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_owned_item", { id })),
	listPlanItems: () => typedError<PlanItemRow[], string>(__TAURI_INVOKE("list_plan_items")),
	createPlanItem: (form: PlanItemFormDto) => typedError<ShoppingPlanItemDto_Serialize, string>(__TAURI_INVOKE("create_plan_item", { form })),
	updatePlanItem: (form: PlanItemFormDto) => typedError<ShoppingPlanItemDto_Serialize, string>(__TAURI_INVOKE("update_plan_item", { form })),
	deletePlanItem: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_plan_item", { id })),
	listShoppingPageContents: (contentType: string | null) => typedError<PageContentRow[], string>(__TAURI_INVOKE("list_shopping_page_contents", { contentType })),
	createShoppingPageContent: (form: PageContentFormDto) => typedError<PageContentRow, string>(__TAURI_INVOKE("create_shopping_page_content", { form })),
	updateShoppingPageContent: (form: PageContentFormDto) => typedError<PageContentRow, string>(__TAURI_INVOKE("update_shopping_page_content", { form })),
	deleteShoppingPageContent: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_shopping_page_content", { id })),
	createSystemDefinition: (form: SystemDefinitionFormDto) => typedError<null, string>(__TAURI_INVOKE("create_system_definition", { form })),
	updateSystemDefinition: (form: SystemDefinitionFormDto) => typedError<null, string>(__TAURI_INVOKE("update_system_definition", { form })),
	listPurchaseLanes: () => typedError<PurchaseLaneRow[], string>(__TAURI_INVOKE("list_purchase_lanes")),
	reorderSystemDefinitions: (orderedIds: string[]) => typedError<null, string>(__TAURI_INVOKE("reorder_system_definitions", { orderedIds })),
	reorderShoppingPageContents: (orderedIds: string[]) => typedError<null, string>(__TAURI_INVOKE("reorder_shopping_page_contents", { orderedIds })),
};

/* Types */
export type OwnedItemFormDto = {
	id?: string | null,
	name: string,
	system: string,
	category: string,
	spaces: string[],
	stages: string[],
	necessity: string,
	lifecycle: string,
	depreciation: string | null,
	quantity: number,
	status: string,
	replacementCue: string,
	note: string,
};

export type OwnedItemRow = {
	id: string,
	name: string,
	system_id: string,
	category: string,
	necessity: string,
	lifecycle: string,
	depreciation: string | null,
	quantity: number,
	status: string,
	replacement_cue: string,
	note: string,
	sort_order: number,
	is_archived: boolean,
	created_at: string,
	updated_at: string,
};

export type PageContentFormDto = {
	id?: string | null,
	contentType: string,
	title: string | null,
	stage: string | null,
	system: string | null,
	summary: string | null,
	reason: string | null,
	body: string,
};

export type PageContentRow = {
	id: string,
	content_type: string,
	title: string | null,
	stage: string | null,
	system_id: string | null,
	summary: string | null,
	reason: string | null,
	body_json: string,
	sort_order: number,
	is_enabled: boolean,
	created_at: string,
	updated_at: string,
};

export type PlanItemFormDto = {
	id?: string | null,
	laneId: string,
	name: string,
	system: string,
	category: string,
	spaces: string[],
	stages: string[],
	necessity: string,
	lifecycle: string,
	depreciation: string | null,
	reason: string,
	targetLifestyle: string,
	currentPrice: number | null,
	buyBelowPrice: number | null,
	overpayPrice: number | null,
	note: string,
	tags: string[],
	keywords: string[],
};

export type PlanItemRow = {
	id: string,
	lane_id: string,
	name: string,
	system_id: string,
	category: string,
	necessity: string,
	lifecycle: string,
	depreciation: string | null,
	reason: string,
	target_lifestyle: string,
	current_price: number | null,
	buy_below_price: number | null,
	overpay_price: number | null,
	note: string,
	sort_order: number,
	is_archived: boolean,
	created_at: string,
	updated_at: string,
};

export type PurchaseLaneRow = {
	id: string,
	title: string,
	subtitle: string,
	sort_order: number,
	is_enabled: boolean,
	created_at: string,
	updated_at: string,
};

export type ShoppingBoundaryEntryDto = {
	id: string,
	item: string,
	system: string,
	reason: string,
};

export type ShoppingItemBaseDto = ShoppingItemBaseDto_Serialize | ShoppingItemBaseDto_Deserialize;

export type ShoppingItemBaseDto_Deserialize = {
	system: string,
	category: string,
	spaces: string[],
	stages: string[],
	necessity: string,
	lifecycle: string,
	depreciation: string | null,
};

export type ShoppingItemBaseDto_Serialize = {
	system: string,
	category: string,
	spaces: string[],
	stages: string[],
	necessity: string,
	lifecycle: string,
	depreciation?: string | null,
};

export type ShoppingLifestyleCollectionDto = {
	id: string,
	title: string,
	description: string,
	items: string[],
};

export type ShoppingModuleDto = ShoppingModuleDto_Serialize | ShoppingModuleDto_Deserialize;

export type ShoppingModuleDto_Deserialize = {
	systemDefinitions: ShoppingSystemDefinitionDto[],
	spaceDefinitions: ShoppingSpaceDefinitionDto[],
	spotlights: ShoppingSpotlightDto[],
	ownedItems: ShoppingOwnedItemDto_Deserialize[],
	purchaseLanes: ShoppingPurchaseLaneDto_Deserialize[],
	stageChecklists: ShoppingStageChecklistDto[],
	priceReferences: ShoppingPriceReferenceDto_Deserialize[],
	boundaryEntries: ShoppingBoundaryEntryDto[],
	lifestyleCollections: ShoppingLifestyleCollectionDto[],
};

export type ShoppingModuleDto_Serialize = {
	systemDefinitions: ShoppingSystemDefinitionDto[],
	spaceDefinitions: ShoppingSpaceDefinitionDto[],
	spotlights: ShoppingSpotlightDto[],
	ownedItems: ShoppingOwnedItemDto_Serialize[],
	purchaseLanes: ShoppingPurchaseLaneDto_Serialize[],
	stageChecklists: ShoppingStageChecklistDto[],
	priceReferences: ShoppingPriceReferenceDto_Serialize[],
	boundaryEntries: ShoppingBoundaryEntryDto[],
	lifestyleCollections: ShoppingLifestyleCollectionDto[],
};

export type ShoppingOwnedItemDto = ShoppingOwnedItemDto_Serialize | ShoppingOwnedItemDto_Deserialize;

export type ShoppingOwnedItemDto_Deserialize = {
	id: string,
	name: string,
	quantity: number,
	status: string,
	replacementCue: string,
	note: string,
} & ShoppingItemBaseDto_Deserialize;

export type ShoppingOwnedItemDto_Serialize = {
	id: string,
	name: string,
	quantity: number,
	status: string,
	replacementCue: string,
	note: string,
} & ShoppingItemBaseDto_Serialize;

export type ShoppingPlanItemDto = ShoppingPlanItemDto_Serialize | ShoppingPlanItemDto_Deserialize;

export type ShoppingPlanItemDto_Deserialize = {
	id: string,
	name: string,
	reason: string,
	targetLifestyle: string,
	currentPrice: number | null,
	buyBelowPrice: number | null,
	overpayPrice: number | null,
	note: string,
	tags: string[],
	keywords: string[],
} & ShoppingItemBaseDto_Deserialize;

export type ShoppingPlanItemDto_Serialize = {
	id: string,
	name: string,
	reason: string,
	targetLifestyle: string,
	currentPrice: number | null,
	buyBelowPrice: number | null,
	overpayPrice: number | null,
	note: string,
	tags: string[],
	keywords: string[],
} & ShoppingItemBaseDto_Serialize;

export type ShoppingPriceReferenceDto = ShoppingPriceReferenceDto_Serialize | ShoppingPriceReferenceDto_Deserialize;

export type ShoppingPriceReferenceDto_Deserialize = {
	id: string,
	system: string,
	category: string,
	lifecycle: string,
	depreciation: string | null,
	entryPrice: number | null,
	sweetSpotPrice: number | null,
	overpayPrice: number | null,
	note: string,
};

export type ShoppingPriceReferenceDto_Serialize = {
	id: string,
	system: string,
	category: string,
	lifecycle: string,
	depreciation?: string | null,
	entryPrice: number | null,
	sweetSpotPrice: number | null,
	overpayPrice: number | null,
	note: string,
};

export type ShoppingPurchaseLaneDto = ShoppingPurchaseLaneDto_Serialize | ShoppingPurchaseLaneDto_Deserialize;

export type ShoppingPurchaseLaneDto_Deserialize = {
	id: string,
	title: string,
	subtitle: string,
	items: ShoppingPlanItemDto_Deserialize[],
};

export type ShoppingPurchaseLaneDto_Serialize = {
	id: string,
	title: string,
	subtitle: string,
	items: ShoppingPlanItemDto_Serialize[],
};

export type ShoppingSpaceDefinitionDto = {
	id: string,
	name: string,
};

export type ShoppingSpotlightDto = {
	id: string,
	title: string,
	stage: string,
	summary: string,
	reason: string,
	attention: string[],
};

export type ShoppingStageChecklistDto = {
	id: string,
	stage: string,
	title: string,
	description: string,
	focus: string,
	sections: ShoppingStageChecklistSectionDto[],
};

export type ShoppingStageChecklistSectionDto = {
	system: string,
	minimum: string[],
	essentials: string[],
	upgrades: string[],
};

export type ShoppingSystemDefinitionDto = {
	id: string,
	cluster: string,
	summary: string,
	keyQuestion: string,
	secondaryGroups: string[],
};

export type SystemDefinitionFormDto = {
	id: string,
	cluster: string,
	summary: string,
	keyQuestion: string,
	secondaryGroups: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

