// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	getBeliefs: () => typedError<BeliefsModuleDto_Serialize, string>(__TAURI_INVOKE("get_beliefs")),
	createBeliefEntry: (form: BeliefEntryFormDto) => typedError<BeliefEntryDto_Serialize, string>(__TAURI_INVOKE("create_belief_entry", { form })),
	updateBeliefEntry: (form: BeliefEntryFormDto) => typedError<BeliefEntryDto_Serialize, string>(__TAURI_INVOKE("update_belief_entry", { form })),
	deleteBeliefEntry: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_belief_entry", { id })),
	getLegacy: () => typedError<LegacyModuleDto_Serialize, string>(__TAURI_INVOKE("get_legacy")),
	listLegacyItems: () => typedError<LegacyItemDto_Serialize[], string>(__TAURI_INVOKE("list_legacy_items")),
	createLegacyItem: (form: LegacyItemFormDto) => typedError<LegacyItemDto_Serialize, string>(__TAURI_INVOKE("create_legacy_item", { form })),
	updateLegacyItem: (form: LegacyItemFormDto) => typedError<LegacyItemDto_Serialize, string>(__TAURI_INVOKE("update_legacy_item", { form })),
	deleteLegacyItem: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_legacy_item", { id })),
	getShopping: () => typedError<ShoppingModuleDto_Serialize, string>(__TAURI_INVOKE("get_shopping")),
	listShoppingItems: () => typedError<ShoppingItemDto_Serialize[], string>(__TAURI_INVOKE("list_shopping_items")),
	createShoppingItem: (form: ItemFormDto) => typedError<ShoppingItemDto_Serialize, string>(__TAURI_INVOKE("create_shopping_item", { form })),
	updateShoppingItem: (form: ItemFormDto) => typedError<ShoppingItemDto_Serialize, string>(__TAURI_INVOKE("update_shopping_item", { form })),
	deleteShoppingItem: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_shopping_item", { id })),
	listShoppingStageTemplates: () => typedError<ShoppingStageTemplateDto[], string>(__TAURI_INVOKE("list_shopping_stage_templates")),
	createShoppingStageTemplate: (form: StageTemplateFormDto) => typedError<ShoppingStageTemplateDto, string>(__TAURI_INVOKE("create_shopping_stage_template", { form })),
	updateShoppingStageTemplate: (form: StageTemplateFormDto) => typedError<ShoppingStageTemplateDto, string>(__TAURI_INVOKE("update_shopping_stage_template", { form })),
	deleteShoppingStageTemplate: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_shopping_stage_template", { id })),
	reorderStageTemplates: (orderedIds: string[]) => typedError<null, string>(__TAURI_INVOKE("reorder_stage_templates", { orderedIds })),
	listShoppingSpaceDefinitions: () => typedError<ShoppingSpaceDefinitionDto[], string>(__TAURI_INVOKE("list_shopping_space_definitions")),
	listShoppingAttributeDefinitions: () => typedError<ShoppingAttributeDefinitionDto_Serialize[], string>(__TAURI_INVOKE("list_shopping_attribute_definitions")),
	listShoppingAttributeDefinitionsForManagement: () => typedError<ShoppingAttributeDefinitionDto_Serialize[], string>(__TAURI_INVOKE("list_shopping_attribute_definitions_for_management")),
	createShoppingAttributeDefinition: (form: AttributeDefinitionFormDto) => typedError<ShoppingAttributeDefinitionDto_Serialize, string>(__TAURI_INVOKE("create_shopping_attribute_definition", { form })),
	updateShoppingAttributeDefinition: (form: AttributeDefinitionFormDto) => typedError<ShoppingAttributeDefinitionDto_Serialize, string>(__TAURI_INVOKE("update_shopping_attribute_definition", { form })),
	disableShoppingAttributeDefinition: (id: string, version: number) => typedError<null, string>(__TAURI_INVOKE("disable_shopping_attribute_definition", { id, version })),
	enableShoppingAttributeDefinition: (id: string, version: number) => typedError<null, string>(__TAURI_INVOKE("enable_shopping_attribute_definition", { id, version })),
	reorderShoppingAttributeDefinitions: (kind: string, orderedIds: string[]) => typedError<null, string>(__TAURI_INVOKE("reorder_shopping_attribute_definitions", { kind, orderedIds })),
	createShoppingSpaceDefinition: (form: SpaceDefinitionFormDto) => typedError<ShoppingSpaceDefinitionDto, string>(__TAURI_INVOKE("create_shopping_space_definition", { form })),
	updateShoppingSpaceDefinition: (form: SpaceDefinitionFormDto) => typedError<ShoppingSpaceDefinitionDto, string>(__TAURI_INVOKE("update_shopping_space_definition", { form })),
	deleteShoppingSpaceDefinition: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_shopping_space_definition", { id })),
	reorderSpaceDefinitions: (orderedIds: string[]) => typedError<null, string>(__TAURI_INVOKE("reorder_space_definitions", { orderedIds })),
	listShoppingPageContents: (contentType: string | null) => typedError<PageContentRow[], string>(__TAURI_INVOKE("list_shopping_page_contents", { contentType })),
	createShoppingPageContent: (form: PageContentFormDto) => typedError<PageContentRow, string>(__TAURI_INVOKE("create_shopping_page_content", { form })),
	updateShoppingPageContent: (form: PageContentFormDto) => typedError<PageContentRow, string>(__TAURI_INVOKE("update_shopping_page_content", { form })),
	deleteShoppingPageContent: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_shopping_page_content", { id })),
	createSystemDefinition: (form: SystemDefinitionFormDto) => typedError<null, string>(__TAURI_INVOKE("create_system_definition", { form })),
	updateSystemDefinition: (form: SystemDefinitionFormDto) => typedError<null, string>(__TAURI_INVOKE("update_system_definition", { form })),
	deleteSystemDefinition: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_system_definition", { id })),
	reorderSystemDefinitions: (orderedIds: string[]) => typedError<null, string>(__TAURI_INVOKE("reorder_system_definitions", { orderedIds })),
	assignSystemDefinitionItems: (systemId: string, itemIds: string[]) => typedError<null, string>(__TAURI_INVOKE("assign_system_definition_items", { systemId, itemIds })),
	assignSpaceDefinitionItems: (spaceId: string, itemIds: string[]) => typedError<null, string>(__TAURI_INVOKE("assign_space_definition_items", { spaceId, itemIds })),
	reorderShoppingPageContents: (orderedIds: string[]) => typedError<null, string>(__TAURI_INVOKE("reorder_shopping_page_contents", { orderedIds })),
	countItemsUsingShoppingAttribute: (kind: string, code: string) => typedError<number, string>(__TAURI_INVOKE("count_items_using_shopping_attribute", { kind, code })),
};

/* Types */
export type AttributeDefinitionFormDto = {
	id?: string | null,
	kind: string,
	code: string,
	semanticKey?: string | null,
	label: string,
	labelEn?: string | null,
	description?: string,
	styleToken?: string | null,
	rank?: number | null,
	isEnabled?: boolean,
	/**  乐观锁版本号；更新/启停时回传读到的版本，创建时忽略 */
	version?: number,
};

export type BeliefCardDto = {
	id: string,
	label: string,
	summary: string,
	note: string,
	keywords: string[],
};

export type BeliefEntryDto = BeliefEntryDto_Serialize | BeliefEntryDto_Deserialize;

export type BeliefEntryDto_Deserialize = {
	id: string,
	title: string,
	statement: string,
	description: string,
	domain: string,
	layer: string,
	stability: string,
	source: string,
	impact: string,
	secondaryDomains?: string[],
	cbtLayer: string | null,
	cognitiveDistortions?: string[],
	defenseMechanism: string | null,
	attachmentNote: string | null,
	revisionHistory?: BeliefRevisionDto[],
	tags?: string[],
};

export type BeliefEntryDto_Serialize = {
	id: string,
	title: string,
	statement: string,
	description: string,
	domain: string,
	layer: string,
	stability: string,
	source: string,
	impact: string,
	secondaryDomains?: string[],
	cbtLayer?: string | null,
	cognitiveDistortions?: string[],
	defenseMechanism?: string | null,
	attachmentNote?: string | null,
	revisionHistory: BeliefRevisionDto[],
	tags: string[],
};

export type BeliefEntryFormDto = {
	id?: string | null,
	title: string,
	statement: string,
	description?: string,
	domain: string,
	layer: string,
	stability: string,
	source: string,
	impact: string,
	secondaryDomains?: string[],
	cbtLayer?: string | null,
	cognitiveDistortions?: string[],
	defenseMechanism?: string | null,
	attachmentNote?: string | null,
	revisionHistory?: BeliefRevisionDto[],
	tags?: string[],
};

export type BeliefRelationDto = {
	id: string,
	type: string,
	fromId: string,
	toId: string,
	note: string,
};

export type BeliefRevisionDto = {
	id: string,
	date: string,
	summary: string,
	changedFields: string[],
};

export type BeliefsModuleDto = BeliefsModuleDto_Serialize | BeliefsModuleDto_Deserialize;

export type BeliefsModuleDto_Deserialize = {
	cards: BeliefCardDto[],
	questions: string[],
	entries: BeliefEntryDto_Deserialize[],
	relations: BeliefRelationDto[],
	attachmentReflection: string,
};

export type BeliefsModuleDto_Serialize = {
	cards: BeliefCardDto[],
	questions: string[],
	entries: BeliefEntryDto_Serialize[],
	relations: BeliefRelationDto[],
	attachmentReflection: string,
};

export type ItemChildChannelFormDto = {
	id?: string | null,
	channel: string,
	entryPrice?: number | null,
	sweetSpotPrice?: number | null,
	overpayPrice?: number | null,
};

export type ItemChildFormDto = {
	id?: string | null,
	name: string,
	status?: string | null,
	lifecycle?: string | null,
	depreciation?: string | null,
	channelPrices?: ItemChildChannelFormDto[],
};

export type ItemFormDto = {
	id?: string | null,
	name: string,
	children: ItemChildFormDto[],
	systemTags: string[],
	spaceTags: string[],
	note?: string,
};

export type LegacyItemDto = LegacyItemDto_Serialize | LegacyItemDto_Deserialize;

export type LegacyItemDto_Deserialize = {
	id: string,
	title: string,
	category: string,
	recipient: string,
	recipientName: string | null,
	relatedRelationshipId: string | null,
	urgency: string,
	visibility: string,
	deliveryCondition: string | null,
	status: string,
	emotionalLoad: string | null,
	summary: string,
	content: string,
	contentPreview: string,
	isLocked: boolean,
	requiresSecondConfirm: boolean,
	excludeFromAi: boolean,
	createdAt: string,
	updatedAt: string,
	finalizedAt: string | null,
	reviewCue: string,
	tags?: string[],
};

export type LegacyItemDto_Serialize = {
	id: string,
	title: string,
	category: string,
	recipient: string,
	recipientName?: string | null,
	relatedRelationshipId?: string | null,
	urgency: string,
	visibility: string,
	deliveryCondition?: string | null,
	status: string,
	emotionalLoad?: string | null,
	summary: string,
	content: string,
	contentPreview: string,
	isLocked: boolean,
	requiresSecondConfirm: boolean,
	excludeFromAi: boolean,
	createdAt: string,
	updatedAt: string,
	finalizedAt?: string | null,
	reviewCue: string,
	tags: string[],
};

export type LegacyItemFormDto = {
	id?: string | null,
	title: string,
	category: string,
	recipient: string,
	recipientName?: string | null,
	relatedRelationshipId?: string | null,
	urgency: string,
	visibility: string,
	deliveryCondition?: string | null,
	status: string,
	emotionalLoad?: string | null,
	summary: string,
	content: string,
	isLocked?: boolean,
	requiresSecondConfirm?: boolean,
	excludeFromAi?: boolean,
	reviewCue?: string,
	tags?: string[],
};

export type LegacyModuleDto = LegacyModuleDto_Serialize | LegacyModuleDto_Deserialize;

export type LegacyModuleDto_Deserialize = {
	items?: LegacyItemDto_Deserialize[],
	trustBoundaries?: LegacyTrustBoundaryDto[],
	reviewPrompts?: string[],
};

export type LegacyModuleDto_Serialize = {
	items: LegacyItemDto_Serialize[],
	trustBoundaries: LegacyTrustBoundaryDto[],
	reviewPrompts: string[],
};

export type LegacyTrustBoundaryDto = {
	id: string,
	title: string,
	detail: string,
};

export type PageContentFormDto = {
	id?: string | null,
	contentType: string,
	title: string | null,
	stage: string | null,
	system: string | null,
	summary: string | null,
	reason: string | null,
	body: string,
};

export type PageContentRow = {
	id: string,
	content_type: string,
	title: string | null,
	stage: string | null,
	system_id: string | null,
	summary: string | null,
	reason: string | null,
	body_json: string,
	sort_order: number,
	is_enabled: boolean,
	created_at: string,
	updated_at: string,
};

export type ShoppingAttributeDefinitionDto = ShoppingAttributeDefinitionDto_Serialize | ShoppingAttributeDefinitionDto_Deserialize;

export type ShoppingAttributeDefinitionDto_Deserialize = {
	id: string,
	kind: string,
	code: string,
	semanticKey: string | null,
	label: string,
	labelEn: string | null,
	description?: string,
	styleToken: string | null,
	rank: number | null,
	sortOrder: number,
	isEnabled: boolean,
	isSystem: boolean,
	/**  乐观锁版本号，前端写回时回传，用于并发冲突检测 */
	version: number,
};

export type ShoppingAttributeDefinitionDto_Serialize = {
	id: string,
	kind: string,
	code: string,
	semanticKey?: string | null,
	label: string,
	labelEn?: string | null,
	description: string,
	styleToken?: string | null,
	rank?: number | null,
	sortOrder: number,
	isEnabled: boolean,
	isSystem: boolean,
	/**  乐观锁版本号，前端写回时回传，用于并发冲突检测 */
	version: number,
};

export type ShoppingBoundaryEntryDto = {
	id: string,
	item: string,
	system: string,
	reason: string,
};

export type ShoppingItemChildChannelDto = ShoppingItemChildChannelDto_Serialize | ShoppingItemChildChannelDto_Deserialize;

export type ShoppingItemChildChannelDto_Deserialize = {
	id: string,
	channel: string,
	entryPrice: number | null,
	sweetSpotPrice: number | null,
	overpayPrice: number | null,
};

export type ShoppingItemChildChannelDto_Serialize = {
	id: string,
	channel: string,
	entryPrice?: number | null,
	sweetSpotPrice?: number | null,
	overpayPrice?: number | null,
};

export type ShoppingItemChildDto = ShoppingItemChildDto_Serialize | ShoppingItemChildDto_Deserialize;

export type ShoppingItemChildDto_Deserialize = {
	id: string,
	name: string,
	status: string | null,
	lifecycle: string | null,
	depreciation: string | null,
	channelPrices?: ShoppingItemChildChannelDto_Deserialize[],
};

export type ShoppingItemChildDto_Serialize = {
	id: string,
	name: string,
	status?: string | null,
	lifecycle?: string | null,
	depreciation?: string | null,
	channelPrices: ShoppingItemChildChannelDto_Serialize[],
};

export type ShoppingItemDto = ShoppingItemDto_Serialize | ShoppingItemDto_Deserialize;

export type ShoppingItemDto_Deserialize = {
	id: string,
	name: string,
	children: ShoppingItemChildDto_Deserialize[],
	systemTags: string[],
	spaceTags: string[],
	note: string,
};

export type ShoppingItemDto_Serialize = {
	id: string,
	name: string,
	children: ShoppingItemChildDto_Serialize[],
	systemTags: string[],
	spaceTags: string[],
	note: string,
};

export type ShoppingLifestyleCollectionDto = {
	id: string,
	title: string,
	description: string,
	items: string[],
};

export type ShoppingModuleDto = ShoppingModuleDto_Serialize | ShoppingModuleDto_Deserialize;

export type ShoppingModuleDto_Deserialize = {
	overview: ShoppingOverviewDto,
	systemDefinitions: ShoppingSystemDefinitionDto[],
	spaceDefinitions: ShoppingSpaceDefinitionDto[],
	attributeDefinitions: ShoppingAttributeDefinitionDto_Deserialize[],
	spotlights: ShoppingSpotlightDto[],
	items: ShoppingItemDto_Deserialize[],
	stageTemplates: ShoppingStageTemplateDto[],
	boundaryEntries: ShoppingBoundaryEntryDto[],
	lifestyleCollections: ShoppingLifestyleCollectionDto[],
};

export type ShoppingModuleDto_Serialize = {
	overview: ShoppingOverviewDto,
	systemDefinitions: ShoppingSystemDefinitionDto[],
	spaceDefinitions: ShoppingSpaceDefinitionDto[],
	attributeDefinitions: ShoppingAttributeDefinitionDto_Serialize[],
	spotlights: ShoppingSpotlightDto[],
	items: ShoppingItemDto_Serialize[],
	stageTemplates: ShoppingStageTemplateDto[],
	boundaryEntries: ShoppingBoundaryEntryDto[],
	lifestyleCollections: ShoppingLifestyleCollectionDto[],
};

export type ShoppingOverviewDimensionPulseDto = {
	id: string,
	name: string,
	itemCount: number,
};

export type ShoppingOverviewDto = {
	totalItems: number,
	ownedItems: number,
	wantedItems: number,
	totalSystems: number,
	totalSpaces: number,
	totalStages: number,
	totalChildren: number,
	totalSpotlights: number,
	totalBoundaryEntries: number,
	totalLifestyleCollections: number,
	topStagePulses: ShoppingOverviewStagePulseDto[],
	topSystemPulses: ShoppingOverviewDimensionPulseDto[],
	topSpacePulses: ShoppingOverviewDimensionPulseDto[],
};

export type ShoppingOverviewStagePulseDto = {
	id: string,
	name: string,
	itemCount: number,
};

export type ShoppingSpaceDefinitionDto = {
	id: string,
	name: string,
	note?: string,
};

export type ShoppingSpotlightDto = {
	id: string,
	title: string,
	stage: string,
	summary: string,
	reason: string,
	attention: string[],
};

export type ShoppingStageItemDto = {
	itemId: string,
	tiers: ShoppingStageItemTiersDto,
};

export type ShoppingStageItemTiersDto = {
	low: string[],
	base: string[],
	up: string[],
};

export type ShoppingStageTemplateDto = {
	id: string,
	name: string,
	description: string,
	focus: string,
	systemDimensionIds: string[],
	spaceDimensionIds: string[],
	items: ShoppingStageItemDto[],
};

export type ShoppingSystemDefinitionDto = {
	id: string,
	name: string,
	summary: string,
	keyQuestion: string,
	secondaryGroups: string[],
};

export type SpaceDefinitionFormDto = {
	id?: string | null,
	name: string,
	note?: string,
};

export type StageItemFormDto = {
	itemId: string,
	tiers: StageItemTiersFormDto,
};

export type StageItemTiersFormDto = {
	low: string[],
	base: string[],
	up: string[],
};

export type StageTemplateFormDto = {
	id?: string | null,
	name: string,
	description?: string,
	focus?: string,
	systemDimensionIds?: string[],
	spaceDimensionIds?: string[],
	items: StageItemFormDto[],
};

export type SystemDefinitionFormDto = {
	id: string,
	name: string,
	summary: string,
	keyQuestion: string,
	secondaryGroups: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

