export const BETTERTOLIVE_API_ENDPOINTS = {
  overview: "/overview",
  reflection: "/reflection",
  events: "/events",
  finance: "/finance",
  shopping: "/shopping",
  emotion: "/emotion",
  crisis: "/crisis",
  beliefs: "/beliefs",
  principles: "/principles",
  relationships: "/relationships",
  growth: "/growth",
  memory: "/memory",
  legacy: "/legacy",
  future: "/future",
  snapshot: "/workspace",
} as const
